### ISSUE TITLE
Download as PDF/PNG broken

### ISSUE THREAD

**Issue by TGCrystal** [OpenCircuits/OpenCircuits#598]
**Describe the bug**
Download as PDF and Download as PNG both cause errors

**To Reproduce**
1. Go to the latest version of the master branch
2. Click the download dropdown on the right side of the header
3. Select Download as PDF or Download as PNG

**Expected behavior**
The circuit is downloaded as a pdf or png

**Desktop:**
 - OS: Windows 10
 - Browser Chrome

**Smartphone:**
 - Device: iPhone 6s Plus
 - OS: iOS 14.4
 - Browser Safari

**Additional context**
This happens regardless of if there is a circuit on the canvas.
From the error messages, it looks like canvas.current is null

**Comment by LeonMontealegre** [comment]
Yep! I created the reference to the canvas 
https://github.com/OpenCircuits/OpenCircuits/blob/15eccc57299f5fb25b2630b2d499baed5ba62bc0/src/site/pages/digital/src/containers/App/index.tsx#L70

And then never attached it to `MainDesigner` as a reference so that it could connect to the actual canvas. 🙃
