### ISSUE TITLE
Segment display sometimes connects wires to wrong ports

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#610]
When attaching a wire to a port of a segment display, it will often attach to the port above the intended one, even if the cursor is directly over the center of the port. After connecting to the incorrect port, if the wire is again dragged to the same port, it will then correctly connect.

I suspect this happens because the port hitboxes are oversized (which by itself isn't an issue), but when selecting an overlapping region no check is done to see which port the cursor is actually closest to. Currently the precedence appears to be to prioritize ports closer to the top of the segment display (that is, top during default orientation. When rotated 180 degrees, the now bottom port is still the highest precedence).

**Comment by LeonMontealegre** [comment]
How to go about fixing this:
The problem is that, as Owen mentioned, the precedence is from top-to-bottom when it should instead be from closest-in-distance to farthest-in-distance.
This comes at the expense of speed, but checking for a point within a circle is extremely fast so hopefully it shouldn't be too much of a problem
