### ISSUE TITLE
IC's remembering previous titles

### ISSUE THREAD

**Issue by Xystem4** [OpenCircuits/OpenCircuits#639]
**Describe the bug**
When making multiple IC's, upon subsequent creations the previous name will still be in the title box (despite not being shown in the preview or the actual created IC unless the user updates the title in some way (deletes/adds at least one character)). If the user replaces it with a new shorter name, the created IC will still widen to the width of the longer, original name (although it will display the correct, new name).

**To Reproduce**
1. Create some valid grouping of components that can form an IC (my go-to being two switches going into an xor gate going into an LED)
2. Select the components, and choose the "Create IC" option
3. Give the IC some title, such as "Testing Title", and confirm
4. Repeat steps 1 & 2 for some new grouping of components
5. Observe the previous title is already in the "IC Name" box, and the preview has already fit the width of _that_ title.
6. Put in a new, shorter name, such as "Test Title", and confirm
7. Observe that the created IC is the same width as the first IC, despite having a shorter name

**Expected behavior**
The second time an IC is created, the title input box should still display "IC Name", and the preview should be the default width. Upon creating a new IC with a shorter name than the previous IC, it should adjust its width to the current title, not the previous one.

**Screenshots**
Example canvas:
![1](https://user-images.githubusercontent.com/65842664/114825511-531c0d00-9d94-11eb-9aeb-8171e1d971fb.png)
After selecting the upper group of components and assigning them the title "Testing Title":
![2](https://user-images.githubusercontent.com/65842664/114825602-6d55eb00-9d94-11eb-8a10-cb9a9e45aa70.png)
After selecting the lower group of components, _before_ adding anything to the title box:
![3](https://user-images.githubusercontent.com/65842664/114825654-8199e800-9d94-11eb-9885-03bc2b9999ec.png)
What the two resulting IC's look like next to one another (after changing the second one's title to "Test Title"):
![4](https://user-images.githubusercontent.com/65842664/114825719-937b8b00-9d94-11eb-9747-ad568891a5f0.png)
What we would have expected to appear when opening the "Create IC" menu for the lower group of components:
![6](https://user-images.githubusercontent.com/65842664/114825877-c02fa280-9d94-11eb-9ff7-99b9b416c71a.png)
What we would have expected the resulting IC's width to look like:
![5](https://user-images.githubusercontent.com/65842664/114825920-cd4c9180-9d94-11eb-8adb-518905232789.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

**Additional context**
Also visible in screenshot 2 above is some strange behavior when filling in the title field of the IC, in that the text expands in the preview without expanding the IC itself, resulting in some overlapping text. But I will document that further in a later issue

**Comment by ezier** [comment]
Behavior from bug report is not reproducing, so issue appears to already have been resolved. When making multiple ICs, the input box displays "IC Name" every time, and the width adjusts to the length of the new title.
Example canvas:
![image](https://user-images.githubusercontent.com/65986539/136098137-d6980e1c-7e06-4d6e-89ca-393c85f61d94.png)

After selecting the upper group of components and assigning them the title "Testing Title":
![image](https://user-images.githubusercontent.com/65986539/136099890-7492c591-2f56-484f-a0d3-447299a2d7b7.png)

After selecting the lower group of components, before adding anything to the title box:
![image](https://user-images.githubusercontent.com/65986539/136100113-74811700-e89e-4234-9653-d0b49a80fc0d.png)

What the resulting IC's look like next to one another (after changing the other two's titles):
![image](https://user-images.githubusercontent.com/65986539/136100324-5e68033f-3b0e-4215-ac58-058aa10b2db7.png)

This is all expected behavior, on windows 10 and in chrome browser.
