### ISSUE TITLE
Encoder "input count" misleading, should be "output count"

### ISSUE THREAD

**Issue by LeonMontealegre** [OpenCircuits/OpenCircuits#66]
Encoder "input count" being the text displayed when selected

**Comment by LeonMontealegre** [comment]
This should be simple but it's not since we'll have to add either the ability to specify the text in the SelectionPopup or have another hidden text field that says "Output count" and then hide/show specifically for Encoder. TBD

**Comment by nprisament** [comment]
Output count should be a separate field that is hidden by default because with IC and microcontrollers, the user should be able to separately define both the number of inputs and outputs of the given IC or microcontroller (probably through the selection popup, or through both the popup and through a separate ic/mc menu)

**Comment by LeonMontealegre** [comment]
Yeah, makes sense to me.
@baxtea

**Comment by nprisament** [comment]
maybe "input count" and "output count" could have flags in the component class where ic is set to true by default and oc is set to false by default, but they can be overwritten by children.
