### ISSUE TITLE
ItemNav gone on Mobile

### ISSUE THREAD

**Issue by SamooMei** [OpenCircuits/OpenCircuits#683]
**Describe the bug**
ItemNav is just straight up gone in Mobile

**To Reproduce**
1. Go to Nightly on Mobile

**Expected behavior**
Item Nav shows up on the bottom as usual

**Screenshots**
![A](https://user-images.githubusercontent.com/43279636/127726039-ceb15a84-39fd-4005-93b7-55774e8dee19.jpg)

**Smartphone (please complete the following information):**
 - Device: [S20 Ultra, iPad Air 2]
 - OS: [iOS, Android]
 - Browser: [Safari, Firefox]

**Comment by thedomino1313** [comment]
Item Nav is not straight up gone, however the calculations for the entire app dimensions do not account for other additions to the screen, such as the tab at the top, and another tab at the bottom on safari. I found that if I scrolled down on the page, the Item Nav was in fact there, but the entire app extended farther than the screen could display. (Due to basing its calculations on the screen height and not the height of its available screen height. )[This website](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) has some combination js and css code that can calculate the available screen height, but it did weird things to the positioning of the Nav on PC. Leon has suggested refactoring the entire nav in a separate html file in order to better fix the problem, but that is beyond my scope of knowledge.
