### ISSUE TITLE
Add touch-pad gesture recognition

### ISSUE THREAD

**Issue by BaiTueeChuan** [OpenCircuits/OpenCircuits#745]
When you use touchpad on laptop to zoom in the circuit, this will both zoom in the circuit and brower, which is inconvenient.

**Comment by OwenMcGee** [comment]
To zoom on touchpad you can do the scroll action rather than the zoom action. I believe stopping the browser from zooming is out of our hands as zooming on touchpad is essentially the same as doing ctrl+ or ctrl- on keyboard. Although I definitely also find myself zooming instead of scrolling when using my laptop.

**Comment by LeonMontealegre** [comment]
We should absolutely be able to capture this event, see Google Maps which has this ability w/o zooming in the entire browser screen
